### ISSUE TITLE
Migration to the new Cosmos SDK

### ISSUE THREAD

**Issue by jsantanders** [Elfocrash/Cosmonaut#107]
It would be nice to have a Cosmonaut that uses the new Cosmos SDK 3.

**Comment by Elfocrash** [comment]
This will happen eventually but at this point I can’t justify the migration. Other than the way exceptions are thrown and a few other minor features, you are not missing out on any with with the v2. A Cosmonaut v3 will require a lot of effort and testing for so little return since Cosmonaut is supposed to be its own api anyway and it had fixed a lot of the v2 issues that MS fixed with the v3. I will eventually migrate it but I need a solid reason like an EOL of the v2.

**Comment by black-byte** [comment]
Are there any updates on this ?

**Comment by Elfocrash** [comment]
Nothing new. Migrating to v3 is not something that needs to happen per se but rather something that would be nice to happen. I will eventually do it but I am in no rush. The Cosmonaut API would stay the same anyway so the underlying SDK shouldn't affect how Cosmonaut works. 
I made a prototype with basic get, create and query functionality and benchmarked Cosmonaut in v2 and v3. Unless your collection is provisioned on 50k RU/s you won't see any different. Cosmonaut (at least on my production apps) consistently responds with < 5ms response times and v3 trims that down to < 4ms. 
I see the concern because v3 is presented as an awesome SDK, and it is, but it's awesome because v2's API was that bad. Cosmonaut always had an awesome API and v3 doesn't change that.

**Comment by Elfocrash** [comment]
For those interested, Cosmonaut v3-preview1 is out. Please test and report. https://github.com/Elfocrash/Cosmonaut/issues/117
