### ISSUE TITLE
Inserting data using AddAsync()?

### ISSUE THREAD

**Issue by kklan** [Elfocrash/Cosmonaut#14]
Hi,

Sorry to bother you again. I'm very new to this.

1. 

I'm trying to inset data into my cosmosdb collection called AppUsers. 
Basically for my social net app, a person is able to add friend using userId and friendsUserId.
So I want to insert into collection (friendUserId in Friends) where `userId="AXYZ963"`. 
I'm not able to figure out how to do that using cosmonaut and Linq.

Here is my collection:
<img width="601" alt="screen shot 2018-05-20 at 11 29 24 am" src="https://user-images.githubusercontent.com/18134352/40282242-38e34104-5c21-11e8-97c0-af42c38223a8.png">

2. Also is there anyway to return an Id of a newly inserted data?
I did `await _cosmosStore.AddAsync(newUser);` can it return `id` as well?

Thanks
KL

**Comment by Elfocrash** [comment]
1) What I would do is that instead of having a `friends` list for the `AppUser` itself, I would have a `Relationships` collection or shared collection and I would have `firstUserId`, `secondUserId` and an Enum `RelationshipType` which would represent the relationship between to users. Then you can just query the friends when needed based on the userIds.

2) There are two ways you can do that. 

- You can pre-set it yourself using the `Guid.NewGuid().ToString` method on the `newUser`.
- You can get the result from `AddAsync` which contains an `Entity` property. This property will have the `Id` set to the one generated for this object.

**Comment by kklan** [comment]
Thanks, can you provide a sample Model.cs example?. 
1. Would it look something like this?

`[CosmosCollection("Relationships")]
     public class Relation
     {
        [JsonProperty(PropertyName = "firstId")]
        public string firstUserId { get; set; }

        [JsonProperty(PropertyName = "secondId")]
        public string secondUserId { get; set; }

        public enum RelationShipStatus { Friends, NotFriends };
     }`

2. I was trying to run SQL query directly instead using `var query = await _cosmosStore.QueryMultipleAsync()` but it is not found. There is only `Query()` available. Is there anyway I can use direct SQL syntax to insert data?

**Comment by Elfocrash** [comment]
Assuming you mean adding to the `Friends` list object that you had.
CosmosDB does not support partial document updates yet. That means that you would have query for the user where userId = "ABC" with LINQ, update the object and then use the `UpdateAsync` method to update the whole document.

You're welcome. A start at the repo is highly appreciated 😄

**Comment by kklan** [comment]
Oh I see. Thank you.
