### ISSUE TITLE
Shareable Collections should support PartitionKey

### ISSUE THREAD

**Issue by ryancrawcour** [Elfocrash/Cosmonaut#25]
> _Something worths noting is that because you will use this to share objects partitioning will be virtually impossible. For that reason the id will be used as a partition key by default as it is the only property that will be definately shared between all objects._

When using Collection Sharing you say that only id can be used. But this is a major limitation imho. You should allow for a PartitionKey to be set as a property of the shareable interface. 

There may well be cases where different objects have the same field (in the same level of the object / json path) and therefore they can happily co-exist in the same collection and be partitioned. 

Imagine this - 

Device - 
{"deviceId": "foo123",...……..}

Telemetry - 
{"telemetryId":"1", "deviceId": "foo123", ….}
{"telemetryId":"2", "deviceId": "foo123", ….}
{"telemetryId":"3", "deviceId": "foo123", ….}
{"telemetryId":"4", "deviceId": "foo123", ….}

etc. 

If I set PartitionKey as a property on the Shareable Interface then Device and Telemetry could co-exist in the same partitioned collection. No problem. 

So not really an issue. More like a feature request. :)

**Comment by Elfocrash** [comment]
Hello Ryan,

You are totally right, I actually wanted to remove this limitation. 

Still haven’t figured out what would be the best way to tackle it from a coding standpoint (how the consumer will set this partition key even if the two objects don’t have the same interface), but I will come up with something.

Thanks for the feedback.

**Comment by ryancrawcour** [comment]
I can take a look and submit a PR and we can go from there, if you like

**Comment by Elfocrash** [comment]
Currently the way to specify the partition key on the dto level is to use the [CosmosPartitionKey] attribute. This makes Cosmonaut to do all the partition key stuff  automatically. It would be nice if the solution is something along those lines. 

Of course if you can think of something better I’d be more than happy to hear it (or even see it with a PR)

**Comment by Elfocrash** [comment]
Ok after I had a coffee I think I have a plan of attack.

1) Remove the SharedCollection default to `/id` partition key logic.
2) Honor the `[CosmosPartitionKey]` attribute in entities that are part of shared collections.
3) Let the user deal with the errors when they have PartitionKey inconsistencies between two different entities that are sharing a collection but also make the right way to do it really clear in the documentation.

I still have one unanswered question though.
In the `CollectionCreator`'s logic, if they don't specify the `[CosmosPartitionKey]` do I default it to `/id` or do I just create it without a partition key at all, limiting them in 10 GB?

I'm leaning towards the second one because it gives more control to the user. What do you think?

**Comment by Elfocrash** [comment]
Enhancement added!
https://github.com/Elfocrash/Cosmonaut/commit/61bbd0de8c20ef28f5ae6a0d4174be2caf4256d6

Shared collections will no longer default to `id` as a partition key.

Thanks for the suggestion.

**Comment by ryancrawcour** [comment]
Very cool!
