### ISSUE TITLE
Composite indexes - Missing in current SDK

### ISSUE THREAD

**Issue by Mortana89** [Elfocrash/Cosmonaut#94]
We're trying to automatically set up composite indexes to support the rather new feature 'ordering by multiple properties'. 
We wanted to do this by using the CosmosSettings object (we have one for each database), where we specify our common settings. But the current IndexingPolicy does not support Composite indexes.
Upon investigating I noticed that Cosmonaut is still using the 2.x SDK of Cosmos, but that doesn't contain nor SpatialIndexes nor CompositeIndexes.
What's the plan on moving to 3.x? 

See here to see the added properties in 3.x:
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1ccbd05e08870a7a25e2671ea8db5bb766c89c63/Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs

**Comment by Elfocrash** [comment]
Hello @Mortana89

Cosmonaut is still using the v2 because the v3 isn't officially launched as GA yet, so I wouldn't even start migrating if the next version isn't released and stable. I will have to run performance tests once released and decide what I will do with it.

I will most likely be migrating to v3 at some point but there are a few issues with that, namely the fact that the Cosmos DB team used some Cosmonaut names in their SDK so I will need to make sure I create the v3 with the least painful way to migrate. I might have to support multiple versions. Don't you worry though. I will be migrating eventually.

**Comment by Mortana89** [comment]
Alright, thanks for the information!
I was looking for a targetted release date, but MS is always very good in hiding this :)
Do you have an idea?

**Comment by Elfocrash** [comment]
2.11.0 of Cosmonaut will be release later today with an upgrade v2 client to version 2.4.1. This version has both `CompositeIndexes` and `SpatialIndexes`.

**Comment by Elfocrash** [comment]
Fixed in b61fc0161b02b981408f4bff71ab46a98e4eaa4d. Published in 2.11.0: https://www.nuget.org/packages/Cosmonaut/2.11.0

**Comment by Mortana89** [comment]
Thanks!!
